[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.forwardedHeaders]
      trustedIPs = ["0.0.0.0/0"]
      insecure = true
    [entryPoints.web.proxyProtocol]
      insecure = true
  [entryPoints.web-secure]
    address = ":443"
    [entryPoints.web-secure.forwardedHeaders]
      trustedIPs = ["0.0.0.0/0"]
      insecure = true
    [entryPoints.web-secure.proxyProtocol]
      insecure = true

[api]
  insecure = true

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false

#  [providers.file]
#    filename = "/etc/traefik/dynamic.toml"
#    watch = true

#[log]
#  level = "DEBUG"

[accessLog]
  filePath = "/var/log/access.log"
#  format = "foobar"
#  bufferingSize = 42
#  [accessLog.filters]
#    statusCodes = ["400-499"]
#    retryAttempts = true
#    minDuration = 42
  [accessLog.fields]
    defaultMode = "keep"
    [accessLog.fields.headers]
      defaultMode = "keep"

[serversTransport]
  insecureSkipVerify = true

[certificatesResolvers.myresolver.acme]

  # Email address used for registration.
  #
  # Required
  #
  email = "development@micadoproject.eu"

  # File or key used for certificates storage.
  #
  # Required
  #
  storage = "acme.json"

  [certificatesResolvers.myresolver.acme.tlsChallenge]
